name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Instance
        uses: Burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete --exclude=".git" --exclude=".env"
          path: ./
          remote_path: evolution
          remote_host: ec2-44-192-63-173.compute-1.amazonaws.com
          remote_user: ${{ secrets.EC2_USER }}
          remote_key: ${{ secrets.EC2_SSH_KEY }}

      - name: Start application with Docker Compose
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ec2-44-192-63-173.compute-1.amazonaws.com
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            chmod +x run_evolution.sh
            ./run_evolution.sh
